version: '3.4'
networks:
  deploy-guide-dev:
    driver: bridge
services:
  urbanfiesta:
    image: ${DOCKER_REGISTRY-}urbanfiesta
    build:
      context: .
      dockerfile: UrbanFiesta/Dockerfile
    ports:
        - "8888:80"
        - "8443:443"
    networks:
      - deploy-guide-dev
    depends_on:
        - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DBL: UrbanFiesta
    ports:
        - "5432:5432"
    networks:
        - deploy-guide-dev
    volumes:
        - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: