version: '3.4'

networks:
  dev:
    driver: bridge

services:
  urban-fiesta:
    image: docker.io/library/urbanfiesta
    depends_on:
     - "app_db"
    container_name: urbanfiesta_services
    ports:
     - "8088:80"
     - "8443:443"  
    build:
     context: .
     dockerfile: Dockerfile
    environment:
     - ConnectionStrings__DefaultConnection=Server=app_db;Port=5432;Database=UrbanFiesta;Username=postgres;Password=postgres
     - ASPNETCORE_URLS=http://+:80
     - ASPNETCORE_ENVIRONMENT=Development
    networks:
     - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=UrbanFiesta
    ports:
     - "5433:5432"
    restart: always
    volumes:
     - app_data:/var/lib/postgresql/data
    networks: 
     - dev

volumes:
 app_data: