version: '3.4'

services:
  urbanfiesta:
    image: ${DOCKER_REGISTRY-}urbanfiesta
    build:
      context: .
      dockerfile: UrbanFiesta/Dockerfile
    ports:
        - "81:81"
    depends_on:
        - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DBL: UrbanFiesta
    ports:
        - "5432:5432"
    volumes:
        - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: